[package]
name = "sql-visualizer"
version = "3.1.0"
description = "QueryAST Lens"
authors = [""]
license = "MIT"
edition = "2021"
rust-version = "1.60"

[build-dependencies]
tauri-build = { version = "1.5" }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "1.6", features = ["api-all"] }
duckdb = { version = "1.2", features = ["bundled", "chrono"] }
chrono = "0.4"
reqwest = { version = "0.11", features = ["stream"] }
futures-util = "0.3"
tokio = { version = "1", features = ["fs", "io-util", "rt-multi-thread", "time", "macros"] }
tokio-util = { version = "0.7", features = ["codec"] }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
connectorx = { version = "0.4.5", default-features = false, features = ["src_oracle", "src_postgres", "src_mysql", "dst_arrow"] }
arrow = "52.0"
parquet = { version = "52.0", features = ["arrow"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
